image:
  baseRepo: mcr.microsoft.com
  azuredisk:
    repository: /oss/kubernetes-csi/azuredisk-csi
    tag: v2.0.0-beta.2
    pullPolicy: IfNotPresent
  csiProvisioner:
    repository: /oss/kubernetes-csi/csi-provisioner
    tag: v3.1.0
    pullPolicy: IfNotPresent
  csiAttacher:
    repository: /oss/kubernetes-csi/csi-attacher
    tag: v3.4.0
    pullPolicy: IfNotPresent
  csiResizer:
    repository: /oss/kubernetes-csi/csi-resizer
    tag: v1.4.0
    pullPolicy: IfNotPresent
  curl:
    repository: /oss/kubernetes/kubectl
    tag: v1.21.2
    pullPolicy: IfNotPresent
  livenessProbe:
    repository: /oss/kubernetes-csi/livenessprobe
    tag: v2.5.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: /oss/kubernetes-csi/csi-node-driver-registrar
    tag: v2.4.0
    pullPolicy: IfNotPresent
  schedulerExtender:
    repository: /oss/kubernetes-csi/azdiskschedulerextender-csi
    tag: v2.0.0-beta.2
    pullPolicy: IfNotPresent
  kubeScheduler:
    repository: /oss/kubernetes/kube-scheduler
    tag: v1.21.2
    pullPolicy: IfNotPresent

serviceAccount:
  create: true # When true, service accounts will be created for you. Set to false if you want to use your own.
  controller: csi-azuredisk-controller-sa # Name of Service Account to be created or used
  node: csi-azuredisk-node-sa # Name of Service Account to be created or used
  snapshotController: csi-snapshot-controller-sa # Name of Service Account to be created or used
  schedulerExtender: csi-azuredisk-scheduler-extender-sa # Name of Service Account to be created or used

rbac:
  create: true
  name: azuredisk

controller:
  name: csi-azuredisk-controller
  cloudConfigSecretName: azure-cloud-provider
  cloudConfigSecretNamespace: kube-system
  allowEmptyCloudConfig: false
  replicas: 2
  metrics:
    port: 29604
    service:
      enabled: false
      monitor:
        enabled: false
  livenessProbe:
    healthPort: 29602
  runOnMaster: false
  disableAvailabilitySetNodes: true
  provisionerWorkerThreads: 40
  attacherWorkerThreads: 500
  logLevel: 5
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoSchedule"
  hostNetwork: true # this setting could be disabled if controller does not depend on MSI setting
  podLabels: {}
  resources:
    csiProvisioner:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiAttacher:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiResizer:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiSnapshotter:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    livenessProbe:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    azuredisk:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi

node:
  cloudConfigSecretName: azure-cloud-provider
  cloudConfigSecretNamespace: kube-system
  allowEmptyCloudConfig: true
  maxUnavailable: 1
  metrics:
    port: 29605
  logLevel: 5
  livenessProbe:
    healthPort: 29603

schedulerExtender:
  name: csi-azuredisk-scheduler-extender
  replicas: 2
  metrics:
    port: 29606
    service:
      enabled: false
      monitor:
        enabled: false
  servicePort: 8889
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoSchedule"

snapshot:
  enabled: false
  createCRDs: true
  name: csi-snapshot-controller
  image:
    csiSnapshotter:
      repository: /oss/kubernetes-csi/csi-snapshotter
      tag: v5.0.1
      pullPolicy: IfNotPresent
    csiSnapshotController:
      repository: /oss/kubernetes-csi/snapshot-controller
      tag: v5.0.1
      pullPolicy: IfNotPresent
  snapshotController:
    name: csi-snapshot-controller
    replicas: 2
    podLabels: {}
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi

feature:
  enableFSGroupPolicy: true

driver:
  name: disk.csi.azure.com
  objectNamespace: "azure-disk-csi" # The namespace where driver related custom resources are created
  # maximum number of attachable volumes per node,
  # maximum number is defined according to node instance type by default(-1)
  volumeAttachLimit: -1
  customUserAgent: ""
  userAgentSuffix: "OSS-helm"

linux:
  enabled: true
  dsName: csi-azuredisk-node # daemonset name
  kubelet: /var/lib/kubelet
  distro: debian # available values: debian, fedora
  enablePerfOptimization: true
  tolerations:
    - operator: "Exists"
  hostNetwork: true # this setting could be disabled if perfProfile is `none`
  podLabels: {}
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: NotIn
              values:
                - virtual-kubelet
  resources:
    livenessProbe:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    nodeDriverRegistrar:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    azuredisk:
      limits:
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 20Mi

windows:
  enabled: true
  dsName: csi-azuredisk-node-win # daemonset name
  kubelet: 'C:\var\lib\kubelet'
  tolerations:
    - key: "node.kubernetes.io/os"
      operator: "Exists"
      effect: "NoSchedule"
  podLabels: {}
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: NotIn
              values:
                - virtual-kubelet
  resources:
    livenessProbe:
      limits:
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 20Mi
    nodeDriverRegistrar:
      limits:
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 20Mi
    azuredisk:
      limits:
        memory: 400Mi
      requests:
        cpu: 10m
        memory: 20Mi

cloud: AzurePublicCloud

storageClasses:
  create: true
  enableZRS: false
  enableUltraSSD: false
  storageClassNames:
    standardLRS: "azuredisk-standard-hdd-lrs"
    standardSSDLRS: "azuredisk-standard-ssd-lrs"
    standardSSDZRS: "azuredisk-standard-ssd-zrs"
    premiumLRS: "azuredisk-premium-ssd-lrs"
    premiumZRS: "azuredisk-premium-ssd-zrs"
    ultraSSDLRS: "azuredisk-ultra-ssd-lrs"


## Reference to one or more secrets to be used when pulling images
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []
# - name: "image-pull-secret"