/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package podfailure

import "k8s.io/apimachinery/pkg/runtime"

func (in *PodFailure) DeepCopyInto(out *PodFailure) {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.Spec = PodFailureSpec{
		PodName: in.Spec.PodName,
	}
	out.Status = PodFailureStatus{
		FailureType: in.Status.FailureType,
		HeartBeat:   in.Status.HeartBeat,
	}
}

// DeepCopyObject returns a generically typed copy of an object
func (in *PodFailure) DeepCopyObject() runtime.Object {
	out := PodFailure{}
	in.DeepCopyInto(&out)

	return &out
}

// DeepCopyObject returns a generically typed copy of an object
func (in *PodFailureList) DeepCopyObject() runtime.Object {
	out := PodFailureList{}
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta

	if in.Items != nil {
		out.Items = make([]PodFailure, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}

	return &out
}
