/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package podfailure

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type PodFailure struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// spec defines the desired state of an AzVolume.
	// Required.
	Spec PodFailureSpec `json:"spec"`
	// status represents the current state of AzVolume.
	// includes error, state, and volume status
	// +required
	Status PodFailureStatus `json:"status"`
}

type PodFailureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []PodFailure `json:"items"`
}

type PodFailureSpec struct {
	PodName string `json:"podName"`
}

type PodFailureStatus struct {
	FailureType string `json:"failureType"`
	HeartBeat   string `json:"heartbeat"`
}
