{{- if and .Values.schedulerExtender.metrics.service.enabled .Values.schedulerExtender.metrics.service.monitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.schedulerExtender.name }}
  namespace: {{ .Release.Namespace }}
{{ include "azuredisk.labels" . | indent 2 }}
    app: {{ .Values.schedulerExtender.name }}
    release: prometheus 
spec:
  selector:
    matchLabels:
        app: {{ .Values.schedulerExtender.name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: 15s
{{- end -}}
