---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-azuredisk-scheduler-extender-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      leaseDuration: "15s"
      renewDeadline: "10s"
      retryPeriod: "2s"
      resourceLock: leases
      resourceName: csi-azuredisk-scheduler-extender
      resourceNamespace: kube-system
    profiles:
    - schedulerName: csi-azuredisk-scheduler-extender
    extenders:
    - urlPrefix: "http://localhost:8889/azdiskschedulerextender"
      filterVerb: "filter"
      prioritizeVerb: "prioritize"
      weight: 1
      nodeCacheCapable: false
      ignorable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-azuredisk-scheduler-extender
  namespace: kube-system
  labels:
    app: csi-azuredisk-scheduler-extender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csi-azuredisk-scheduler-extender
  template:
    metadata:
      labels:
        app: csi-azuredisk-scheduler-extender
    spec:
      serviceAccountName: csi-azuredisk-scheduler-extender-sa
      volumes:
      - name: csi-azuredisk-scheduler-extender-config
        configMap:
          name: csi-azuredisk-scheduler-extender-config
      containers:
      - name: csi-azuredisk-scheduler
        image: mcr.microsoft.com/oss/kubernetes/kube-scheduler:v1.21.2
        imagePullPolicy: IfNotPresent
        args:
        - kube-scheduler
        - --config=/azdiskschedulerextender/config.yaml
        - --v=5
        - --feature-gates
        - CSIInlineVolume=true,LocalStorageCapacityIsolation=true,ServiceNodeExclusion=true # Add CSIMigration=true,CSIMigrationAzureDisk=true,CSIMigrationAzureDiskComplete=true for CSI Migration support
        volumeMounts:
        - name: csi-azuredisk-scheduler-extender-config
          mountPath: /azdiskschedulerextender
      - name: csi-azuredisk-scheduler-extender
        image: mcr.microsoft.com/oss/kubernetes-csi/azdiskschedulerextender-csi:v2.0.0-beta.2 
        imagePullPolicy: Always
        args:
        - "--port=8889"
        - "--metrics-address=0.0.0.0:29606"
        - "--v=5"
        livenessProbe:
          httpGet:
            path: /ping
            port: extender-port
          failureThreshold: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: extender-port
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /ping
            port: extender-port
          failureThreshold: 20
          periodSeconds: 3
        ports:
          - name: extender-port
            containerPort: 8889
            hostPort: 8889
          - name: metrics-port
            containerPort: 29606
            protocol: TCP