---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-azuredisk-node-sa
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-azuredisk-node-secret-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["disk.csi.azure.com"]
    resources: ["azdrivernodes"]
    verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
  - apiGroups: ["disk.csi.azure.com"]
    resources: ["azvolumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["disk.csi.azure.com"]
    resources: ["azvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["disk.csi.azure.com"]
    resources: ["azdrivernodes/status", "azvolumeattachments/status"]
    verbs: ["get", "patch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-azuredisk-node-secret-binding
subjects:
  - kind: ServiceAccount
    name: csi-azuredisk-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-azuredisk-node-secret-role
  apiGroup: rbac.authorization.k8s.io
