---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: disk.csi.azure.com
  annotations:
    csiDriver: v2.0.0-beta.9
    snapshot: v5.0.1
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
