{{- if and .Values.snapshot.enabled .Values.snapshot.snapshotController.serviceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-snapshot-controller-sa
  namespace: {{ .Release.Namespace }}
{{- end -}}
