/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	versioned "sigs.k8s.io/azuredisk-csi-driver/test/podFailover/apis/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/azuredisk-csi-driver/test/podFailover/apis/client/informers/externalversions/internalinterfaces"
	v1beta1 "sigs.k8s.io/azuredisk-csi-driver/test/podFailover/apis/client/listers/podfailure/v1beta1"
	podfailurev1beta1 "sigs.k8s.io/azuredisk-csi-driver/test/podFailover/apis/podfailure/v1beta1"
)

// PodFailureInformer provides access to a shared informer and lister for
// PodFailures.
type PodFailureInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.PodFailureLister
}

type podFailureInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodFailureInformer constructs a new informer for PodFailure type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodFailureInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodFailureInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodFailureInformer constructs a new informer for PodFailure type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodFailureInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodfailureV1beta1().PodFailures(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodfailureV1beta1().PodFailures(namespace).Watch(context.TODO(), options)
			},
		},
		&podfailurev1beta1.PodFailure{},
		resyncPeriod,
		indexers,
	)
}

func (f *podFailureInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodFailureInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podFailureInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&podfailurev1beta1.PodFailure{}, f.defaultInformer)
}

func (f *podFailureInformer) Lister() v1beta1.PodFailureLister {
	return v1beta1.NewPodFailureLister(f.Informer().GetIndexer())
}
