/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/abhisheksinghbaghel/azuredisk-csi-driver/pkg/apis/azuredisk/v1alpha1"
	scheme "github.com/abhisheksinghbaghel/azuredisk-csi-driver/pkg/apis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AzDriverNodesGetter has a method to return a AzDriverNodeInterface.
// A group's client should implement this interface.
type AzDriverNodesGetter interface {
	AzDriverNodes(namespace string) AzDriverNodeInterface
}

// AzDriverNodeInterface has methods to work with AzDriverNode resources.
type AzDriverNodeInterface interface {
	Create(ctx context.Context, azDriverNode *v1alpha1.AzDriverNode, opts v1.CreateOptions) (*v1alpha1.AzDriverNode, error)
	Update(ctx context.Context, azDriverNode *v1alpha1.AzDriverNode, opts v1.UpdateOptions) (*v1alpha1.AzDriverNode, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AzDriverNode, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AzDriverNodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzDriverNode, err error)
	AzDriverNodeExpansion
}

// azDriverNodes implements AzDriverNodeInterface
type azDriverNodes struct {
	client rest.Interface
	ns     string
}

// newAzDriverNodes returns a AzDriverNodes
func newAzDriverNodes(c *DiskV1alpha1Client, namespace string) *azDriverNodes {
	return &azDriverNodes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azDriverNode, and returns the corresponding azDriverNode object, and an error if there is any.
func (c *azDriverNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AzDriverNode, err error) {
	result = &v1alpha1.AzDriverNode{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azdrivernodes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzDriverNodes that match those selectors.
func (c *azDriverNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AzDriverNodeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AzDriverNodeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azdrivernodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azDriverNodes.
func (c *azDriverNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azdrivernodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a azDriverNode and creates it.  Returns the server's representation of the azDriverNode, and an error, if there is any.
func (c *azDriverNodes) Create(ctx context.Context, azDriverNode *v1alpha1.AzDriverNode, opts v1.CreateOptions) (result *v1alpha1.AzDriverNode, err error) {
	result = &v1alpha1.AzDriverNode{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azdrivernodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azDriverNode).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a azDriverNode and updates it. Returns the server's representation of the azDriverNode, and an error, if there is any.
func (c *azDriverNodes) Update(ctx context.Context, azDriverNode *v1alpha1.AzDriverNode, opts v1.UpdateOptions) (result *v1alpha1.AzDriverNode, err error) {
	result = &v1alpha1.AzDriverNode{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azdrivernodes").
		Name(azDriverNode.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azDriverNode).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the azDriverNode and deletes it. Returns an error if one occurs.
func (c *azDriverNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azdrivernodes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azDriverNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azdrivernodes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched azDriverNode.
func (c *azDriverNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzDriverNode, err error) {
	result = &v1alpha1.AzDriverNode{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azdrivernodes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
