/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/clientset.go

// Package mocksnapshotclient is a generated GoMock package.
package mocksnapshotclient

import (
	reflect "reflect"

	snapshotv1 "github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1"
	snapshotv1beta1 "github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1"
	gomock "go.uber.org/mock/gomock"
	discovery "k8s.io/client-go/discovery"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Discovery mocks base method.
func (m *MockInterface) Discovery() discovery.DiscoveryInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Discovery")
	ret0, _ := ret[0].(discovery.DiscoveryInterface)
	return ret0
}

// Discovery indicates an expected call of Discovery.
func (mr *MockInterfaceMockRecorder) Discovery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Discovery", reflect.TypeOf((*MockInterface)(nil).Discovery))
}

// SnapshotV1beta1 mocks base method.
func (m *MockInterface) SnapshotV1beta1() snapshotv1beta1.SnapshotV1beta1Interface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotV1beta1")
	ret0, _ := ret[0].(snapshotv1beta1.SnapshotV1beta1Interface)
	return ret0
}

// SnapshotV1beta1 indicates an expected call of SnapshotV1beta1.
func (mr *MockInterfaceMockRecorder) SnapshotV1beta1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotV1beta1", reflect.TypeOf((*MockInterface)(nil).SnapshotV1beta1))
}

// SnapshotV1 mocks base method.
func (m *MockInterface) SnapshotV1() snapshotv1.SnapshotV1Interface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotV1")
	ret0, _ := ret[0].(snapshotv1.SnapshotV1Interface)
	return ret0
}

// SnapshotV1 indicates an expected call of SnapshotV1.
func (mr *MockInterfaceMockRecorder) SnapshotV1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotV1", reflect.TypeOf((*MockInterface)(nil).SnapshotV1))
}
