/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	scheme "sigs.k8s.io/azuredisk-csi-driver/test/podFailover/apis/client/clientset/versioned/scheme"
	v1beta1 "sigs.k8s.io/azuredisk-csi-driver/test/podFailover/apis/podfailure/v1beta1"
)

// PodFailuresGetter has a method to return a PodFailureInterface.
// A group's client should implement this interface.
type PodFailuresGetter interface {
	PodFailures(namespace string) PodFailureInterface
}

// PodFailureInterface has methods to work with PodFailure resources.
type PodFailureInterface interface {
	Create(ctx context.Context, podFailure *v1beta1.PodFailure, opts v1.CreateOptions) (*v1beta1.PodFailure, error)
	Update(ctx context.Context, podFailure *v1beta1.PodFailure, opts v1.UpdateOptions) (*v1beta1.PodFailure, error)
	UpdateStatus(ctx context.Context, podFailure *v1beta1.PodFailure, opts v1.UpdateOptions) (*v1beta1.PodFailure, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.PodFailure, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.PodFailureList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.PodFailure, err error)
	PodFailureExpansion
}

// podFailures implements PodFailureInterface
type podFailures struct {
	client rest.Interface
	ns     string
}

// newPodFailures returns a PodFailures
func newPodFailures(c *PodfailureV1beta1Client, namespace string) *podFailures {
	return &podFailures{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the podFailure, and returns the corresponding podFailure object, and an error if there is any.
func (c *podFailures) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.PodFailure, err error) {
	result = &v1beta1.PodFailure{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podfailures").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PodFailures that match those selectors.
func (c *podFailures) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.PodFailureList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.PodFailureList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podfailures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested podFailures.
func (c *podFailures) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("podfailures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a podFailure and creates it.  Returns the server's representation of the podFailure, and an error, if there is any.
func (c *podFailures) Create(ctx context.Context, podFailure *v1beta1.PodFailure, opts v1.CreateOptions) (result *v1beta1.PodFailure, err error) {
	result = &v1beta1.PodFailure{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("podfailures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(podFailure).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a podFailure and updates it. Returns the server's representation of the podFailure, and an error, if there is any.
func (c *podFailures) Update(ctx context.Context, podFailure *v1beta1.PodFailure, opts v1.UpdateOptions) (result *v1beta1.PodFailure, err error) {
	result = &v1beta1.PodFailure{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podfailures").
		Name(podFailure.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(podFailure).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *podFailures) UpdateStatus(ctx context.Context, podFailure *v1beta1.PodFailure, opts v1.UpdateOptions) (result *v1beta1.PodFailure, err error) {
	result = &v1beta1.PodFailure{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podfailures").
		Name(podFailure.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(podFailure).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the podFailure and deletes it. Returns an error if one occurs.
func (c *podFailures) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podfailures").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *podFailures) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podfailures").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched podFailure.
func (c *podFailures) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.PodFailure, err error) {
	result = &v1beta1.PodFailure{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("podfailures").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
