---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk-0
  labels:
    group: myGroup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk-1
  labels:
    group: myGroup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi
