name: Verify
on:
    pull_request: {}
    push: {}
jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Verify
        run: sudo -E -H PATH="$PATH" make verify
