name: Windows Build & Unit Tests
on:
    pull_request: {}
    push: {}

jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.16.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Test
        run: |
          make azuredisk-windows
      - name: Run Windows Unit Tests
        run: |
          # start the CSI Proxy before running tests on windows
          Start-Job -Name CSIProxy -ScriptBlock {
            Invoke-WebRequest https://github.com/andyzhangx/demo/raw/master/windows/csi-proxy-v1.0.0-rc.1.tar.gz -OutFile csi-proxy.tar.gz;
            tar -xvf csi-proxy.tar.gz
            .\bin\csi-proxy.exe --kubelet-path $pwd
          };
          Start-Sleep -Seconds 30;
          Write-Output "getting named pipes"
          [System.IO.Directory]::GetFiles("\\.\\pipe\\")
          go test -v -race ./pkg/...
